services:
  - type: static
    name: oura-health-analyzer
    env: static
    buildCommand: |
      echo "=== STATIC SITE BUILD PROCESS ==="
      echo "Building React frontend for Supabase MCP deployment..."
      cd frontend
      npm install
      npm run build
      echo "Build completed successfully!"
      ls -la build/
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_SUPABASE_URL
        value: https://lgjjzpgnrjzbdcxbkcxh.supabase.co
      - key: REACT_APP_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnamp6cGducmp6YmRjeGJrY3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzIzMzksImV4cCI6MjA3MTc0ODMzOX0.FOnIUD0qdWNicrtxv82qXVdK6w45bgMQLlYmPhQXVAw
