#!/bin/bash

echo "🔧 Setting up Supabase Environment Variables..."
echo ""
echo "📋 You need to set the following environment variables in your Supabase dashboard:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/lgjjzpgnrjzbdcxbkcxh/settings/functions"
echo ""
echo "2. Set these environment variables:"
echo ""
echo "   SUPABASE_URL=https://lgjjzpgnrjzbdcxbkcxh.supabase.co"
echo "   SUPABASE_SERVICE_ROLE_KEY=[Get this from Database > Settings > API]"
echo "   OPENAI_API_KEY=[Your OpenAI API key]"
echo ""
echo "3. After setting the variables, restart the Edge Functions"
echo ""
echo "🔗 Your Supabase project URL: https://lgjjzpgnrjzbdcxbkcxh.supabase.co"
echo "🔑 Your API Key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnamp6cGducmp6YmRjeGJrY3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzIzMzksImV4cCI6MjA3MTc0ODMzOX0.FOnIUD0qdWNicrtxv82qXVdK6w45bgMQLlYmPhQXVAw"
echo ""
echo "✅ Edge Functions deployed successfully!"
echo "✅ Database schema applied!"
echo "✅ Frontend built and ready for deployment!"
echo ""
echo "🚀 Next steps:"
echo "1. Set environment variables in Supabase dashboard"
echo "2. Deploy frontend to Vercel/Netlify"
echo "3. Update frontend API endpoints to use Supabase"
echo "4. Test the application!"
